# Generated by Django 4.1.7 on 2023-03-30 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videogame_store', '0002_loja'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jogo',
            new_name='Jogos',
        ),
        migrations.RenameField(
            model_name='loja',
            old_name='esdereco',
            new_name='endereco',
        ),
    ]
